version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    env_file: ./api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - .:/src
    networks:
      - node-network
  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    ports:
      - "3004:3004"
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

# configure services
mongodb:
  image: mongo:6-jammy
  ports:
    - "27017:27017"
  volumes:
    - dbdata:/data/db
  networks:
    - node-network
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
rabbitmq:
  image: rabbitmq:3-management # this image comes with rabbitmq management interface
  ports:
    - "5672:5672"
    - "15672:15672" # this port expose management tool interface communication
  healthcheck:
    test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    interval: 30s
    timeout: 10s
    retries: 5

# defining volume for mongo db
volumes:
  dbdata:

# network layer communication for mongo db
networks:
  node-network:
    driver: bridge
